package com.spiderg.configurableui;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;

import com.spiderg.viewsDataModel.ViewListData;
import com.spiderg.viewsUtility.AlignmentType;
import com.spiderg.viewsUtility.OrientationType;
import com.spiderg.viewsUtility.ViewGeneratorFactory;


/*
 *  Class which aligns  views based on the view generated by the factory class...
 */
public class MainScreen extends Activity
{
    RelativeLayout      parentView;
    ViewGroup           scrollView, scrollViewChild;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_screen);

        initViewsReferences();

        setOrientation();

        generateViews();
    }


    /*
     *  Initialise the reference of the views in the layout...
     */
    private void initViewsReferences()
    {
        parentView     = (RelativeLayout) findViewById(R.id.rl_activity_main_screen_parent);
    }


    /*
     *
     */
    private void setOrientation()
    {
        if(OrientationType.HORIZONTAL.equalsIgnoreCase(ViewListData.getInstance().orientation))
        {
            scrollView = new HorizontalScrollView(this);
            scrollViewChild = new LinearLayout(this);
            RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                    RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
            scrollView.setLayoutParams(params);

        }
        else if(OrientationType.VERTICAL.equalsIgnoreCase(ViewListData.getInstance().orientation))
        {
            scrollView = new ScrollView(this);
            scrollViewChild = new RelativeLayout(this);
            RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                    RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);
            scrollView.setLayoutParams(params);
        }
        parentView.addView(scrollView);
    }



    /*
     *    Generate the views dynamically based on the JSON data for the view...
     */
    private void generateViews()
    {
        for(int i=0; i<ViewListData.getInstance().getView_Rows().size(); i++ )
        {
            View childView = ViewGeneratorFactory.getDynamicView(i, MainScreen.this);

            if(childView != null)
            {
                childView.setId(i);

                RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                        RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
                if (i > 0)
                {
//                    if(scrollView instanceof  HorizontalScrollView)
//                    {
//                        params.addRule(RelativeLayout.END_OF, i - 1);
//                    }
                    if(scrollView instanceof ScrollView)
                    {
                        params.addRule(RelativeLayout.BELOW, i - 1);
                    }
                }

                alignViews(getViewAlignment(i), params);
                childView.setLayoutParams(params);

                scrollViewChild.addView(childView);
            }
        }
        scrollView.addView(scrollViewChild);
    }


    /*
     *   Align the views on the basis of layout_gravity value in the JSON...
     */
    private void alignViews(String gravity, RelativeLayout.LayoutParams params)
    {
        switch (gravity)
        {
            case AlignmentType.CENTER:
                params.addRule(RelativeLayout.CENTER_IN_PARENT);
                break;
            case AlignmentType.CENTER_HORIZONTAL:
                params.addRule(RelativeLayout.CENTER_HORIZONTAL);
                break;
            case AlignmentType.CENTER_VERTICAL:
                params.addRule(RelativeLayout.CENTER_VERTICAL);
                break;
            case AlignmentType.START:
            case AlignmentType.LEFT:
                params.addRule(RelativeLayout.ALIGN_PARENT_START);
                break;
            case AlignmentType.END:
            case AlignmentType.RIGHT:
                params.addRule(RelativeLayout.ALIGN_PARENT_END);
                break;
            case AlignmentType.TOP:
                params.addRule(RelativeLayout.ALIGN_PARENT_TOP);
                break;
            case AlignmentType.BOTTOM:
                params.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM);
                break;
        }
    }


    private String getViewAlignment(int i)
    {
        return ViewListData.getInstance().getView_Rows().get(i).getViewProperties().getAlignment();
    }



}
